### ISSUE TITLE
Split out data loader and model in the `tf-dist-mnist` template

### ISSUE THREAD

**Issue by dmsuehir** [IntelAI/mlt#151]
Suggestion from @mas-dse-greina to update the `tf-dist-mnist` template to split out the data loader (like, into a `data.py` file) and the model definition (into a `model.py` file). This will make it easier to read and easier for the data scientist to modify without messing up other parts of the code.

**Comment by tonyreina** [comment]
https://github.com/IntelAI/mlt/pull/233

I added this to my PR where I update the templates to a monitored training session. 

Krishna has a cleaner implementation than mine which he'll PR for the Horovod template. I'm hoping to get time to modify mine to his class implementation structure (rather than my dictionary structure). 

However, this code will work and gives the idea of what we're hoping to see. DS will just need to change the code in model.py and data.py and the rest of the stuff is consistent. Should make for a very easy transition for DS into using MLT.

**Comment by dmsuehir** [comment]
Fixed in PR: https://github.com/IntelAI/mlt/pull/301

PR has been merged
