### ISSUE TITLE
Peg pip to version 9.0.3 until newer versions are fixed.

### ISSUE THREAD

**Issue by ashahba** [IntelAI/mlt#373]
Earlier today I noticed all of our builds started failing with due to:
```
py2-e2e create: /usr/share/mlt/.venv
py2-e2e installdeps: -rrequirements.txt, -rrequirements-dev.txt, -e.
ERROR: invocation failed (exit code 1), logfile: /usr/share/mlt/.venv/log/py2-e2e-1.log
ERROR: actionid: py2-e2e
msg: getenv
cmdargs: ['/usr/share/mlt/.venv/bin/pip', 'install', '-rrequirements.txt', '-rrequirements-dev.txt', '-e.']
```
Turns out this is a bug in `pip>=10.0.0` as described here:
https://github.com/scrapy/scrapy/issues/2115
https://github.com/retspen/webvirtcloud/issues/96

**Comment by ashahba** [comment]
Once sample run is here:
https://circleci.com/gh/IntelAI/mlt/1788?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by s1113950** [comment]
The first link you posted relates to missing python system packages; this is most likely due to circleci updating their images yesterday. The second link is about this error: `ReadError: not a gzip file` which is not what you reported 🤔 
I think it's unrelated to `pip` version, but more so related to circleci changing their images and us pulling the latest one always.
I think we can close this ticket.
